### ISSUE TITLE
getting exception of merge operator inside the ngxPermissionsOnly directive

### ISSUE THREAD

**Issue by tanejamohit4** [AlexKhymenko/ngx-permissions#77]
Getting following exception when trying to use ngxPermissionsOnly directive. I have investigated the issue and found that merge operator is not inside the rxjs library. It is inside the rxjs/operators library. Please check this and fix this if this is an issue.

This issue is coming with the latest version which is 6.0.1. But it is working fine with 4.1 version. Please fix this with new version.

ERROR TypeError: rxjs.merge is not a function
    at NgxPermissionsDirective.validateExceptOnlyPermissions (ngx-permissions.umd.js:633)
    at NgxPermissionsDirective.ngOnInit (ngx-permissions.umd.js:612)
    at checkAndUpdateDirectiveInline (core.js:12369)
    at checkAndUpdateNodeInline (core.js:13893)
    at checkAndUpdateNode (core.js:13836)
    at debugCheckAndUpdateNode (core.js:14729)
    at debugCheckDirectivesFn (core.js:14670)
    at Object.eval [as updateDirectives] (MenuComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14655)
    at checkAndUpdateView (core.js:13802)

**Comment by nsacerdote** [comment]
I was also having this same problem. 
In my case, the problem was that I was importing rxjs 5.5.X.
In order to make it work I also ended up using 4.1. 

Copying from the readme.md:
```
With version 5 minimal rxjs dependency 6.0
With version 4 minimal rxjs dependency 5.5
```
IMO there is nothing to fix on latest version (I have to say that I didn't tried to upgrade my rxjs dependency, but I think that should solve the problem)

**Comment by AlexKhymenko** [comment]
@tanejamohit4 here is compatible table https://github.com/AlexKhymenko/ngx-permissions/wiki/Version-dependencies
