### ISSUE TITLE
rxjs.merge is not a function  at NgxPermissionsDirective.validateExceptOnlyPermissions (ngx-permissions.umd.js:632)

### ISSUE THREAD

**Issue by ShaileshInfyom** [AlexKhymenko/ngx-permissions#52]
## I'm submitting a...

update angular 4.2 to 5.2.8 and update ngx-permisison package but not working a
</code></pre>

## Current behavior
Got error
<pre><code> rxjs.merge is not a function
    at NgxPermissionsDirective.validateExceptOnlyPermissions (ngx-permissions.umd.js:632)
    at NgxPermissionsDirective.ngOnInit (ngx-permissions.umd.js:611)
    at checkAndUpdateDirectiveInline (core.js:12411)
    at checkAndUpdateNodeInline (core.js:13935)
    at checkAndUpdateNode (core.js:13878)
    at debugCheckAndUpdateNode (core.js:14771)
    at debugCheckDirectivesFn (core.js:14712)
    at Object.eval [as updateDirectives] (AppSidenavComponent.html:22)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14697)
    at checkAndUpdateView (core.js:13844)
</code></pre>
## Expected behavior
it should be work fine with angular 5.2.8

## Environment

<pre><code>
Angular version: 5.2.8
ngx-permissions version: X.Y.Z
 rxjs: 5.5.6

Browser:
- [ ] Chrome (desktop) version XX

**Comment by ShaileshInfyom** [comment]
sorry my version mismatch

**Comment by seanmavley** [comment]
@ShaileshInfyom Sorry, version mismatch like how?

I have `Angular: 5.2.11` and `"rxjs": "^5.5.11",`

I've updated my project by running `npm update`. Still having the error
