### ISSUE TITLE
TypeError: rxjs_Observable.Observable.merge(...).mergeAll is not a function

### ISSUE THREAD

**Issue by Lantoine44** [AlexKhymenko/ngx-permissions#8]
I'm submitting a Bug report 

## my code in my component (bandeau-qoq.component.ts)
<pre>
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Router } from '@angular/router';
...
import { NgxPermissionsService } from 'ngx-permissions';

@Component({
  selector: 'app-bandeau-qoq',
  templateUrl: './bandeau-qoq.component.html',
  styleUrls: ['./bandeau-qoq.component.less']
})
export class BandeauQoqComponent implements OnInit {
  public isCollapsed = false; // Indique si le bandeau doit être réduit.

  // Enumération 'états des dossiers'
  private etatEnum = EtatEnum;

  private dossierService: DossierService; // Rendre le service accessible dans la vue
  private quoi: TypeSignalement;
  private ou: Regate;
  private quand: QuandForm;
  // Detecter la valeur précédente de la version de dossier
  // Nous aide dans la gestion du cache des données globales
  @Input() isEditMode: boolean;
  @Input() dossier: Dossier;

  @Output() changeSection: EventEmitter<any> = new EventEmitter();
  @Output() validationGlobale: EventEmitter<any> = new EventEmitter();

  constructor(private dossierServiceInj: DossierService,
    private router: Router,
    private app: AppComponent,
    private permissionsService: NgxPermissionsService) {
    this.dossierService = dossierServiceInj;
  }

  ngOnInit() {
    console.log("permission :");
    const perm = ["ADMIN", "EDITOR"];

    this.permissionsService.loadPermissions(perm);
    console.log(this.permissionsService.getPermissions());

</pre>
it's works fine : i can get the permissions in the console

## my code in the template (bandeau-qoq.component.html)

<ng-container *ngxPermissionsOnly="['ADMIN']">

## Current behavior
When i use a directive in the template, the following error appears in the console (chrome)

<pre>
Error: Uncaught (in promise): TypeError: rxjs_Observable.Observable.merge(...).mergeAll is not a function
TypeError: rxjs_Observable.Observable.merge(...).mergeAll is not a function
    at NgxPermissionsService.hasArrayPermission (ngx-permissions.umd.js:189)
</pre>

## Environment

<pre><code>
Angular version: 4.0.0
ngx-permissions version: 2.1.0

Browser: Chrome (desktop) version 61.0.3163.100 (Build officiel) (32 bits)

**Comment by Lantoine44** [comment]
Thank you very much, it works fine with the version 5.4.3 of rxjs whereas it was wrong with the version 5.1.0
